# Generated by Django 4.2.3 on 2023-08-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
