# Generated by Django 4.2.3 on 2023-08-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('imsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.imsbasemodel')),
                ('identifier', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('objective', models.TextField()),
                ('bord', models.CharField(max_length=155, null=True)),
                ('ownership', models.CharField(max_length=155, null=True)),
                ('documents', models.CharField(max_length=155, null=True)),
                ('tan', models.CharField(max_length=155, null=True)),
                ('license', models.CharField(max_length=155, null=True)),
                ('accreditation', models.CharField(max_length=155, null=True)),
                ('approvals', models.CharField(max_length=155, null=True)),
                ('declaration', models.CharField(max_length=155, null=True)),
            ],
            bases=('master.imsbasemodel',),
        ),
    ]
