# Generated by Django 4.1.7 on 2023-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_resume_socialprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='media/resumes/'),
        ),
    ]
